[package]
name = "polkadot-node-core-proposer"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
futures = "0.3.4"
futures-timer = "3.0.1"
log = "0.4.8"
parity-scale-codec = "1.3.4"
polkadot-node-subsystem = { path = "../../subsystem" }
polkadot-overseer = { path = "../../overseer" }
polkadot-primitives = { path = "../../../primitives" }
sc-basic-authorship = { git = "https://github.com/mxinden/substrate", branch = "update-prometheus" }
sc-block-builder = { git = "https://github.com/mxinden/substrate", branch = "update-prometheus" }
sc-client-api = { git = "https://github.com/mxinden/substrate", branch = "update-prometheus" }
sc-telemetry = { git = "https://github.com/mxinden/substrate", branch = "update-prometheus" }
sp-api = { git = "https://github.com/mxinden/substrate", branch = "update-prometheus" }
sp-blockchain = { git = "https://github.com/mxinden/substrate", branch = "update-prometheus" }
sp-consensus = { git = "https://github.com/mxinden/substrate", branch = "update-prometheus" }
sp-core = { git = "https://github.com/mxinden/substrate", branch = "update-prometheus" }
sp-inherents = { git = "https://github.com/mxinden/substrate", branch = "update-prometheus" }
sp-runtime = { git = "https://github.com/mxinden/substrate", branch = "update-prometheus" }
sp-transaction-pool = { git = "https://github.com/mxinden/substrate", branch = "update-prometheus" }
tokio-executor = { version = "0.2.0-alpha.6", features = ["blocking"] }
wasm-timer = "0.2.4"
