[package]
name = "polkadot-test-runtime-client"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
futures = "0.3.1"
codec = { package = "parity-scale-codec", version = "1.3.4" }

# Polkadot dependencies
polkadot-primitives = { path = "../../../primitives" }
polkadot-runtime-common = { path = "../../common" }
polkadot-test-runtime = { path = ".." }
polkadot-test-service = { path = "../../../node/test-service" }

# Substrate dependencies
pallet-timestamp = { git = "https://github.com/mxinden/substrate", branch = "update-prometheus" }
sc-block-builder = { git = "https://github.com/mxinden/substrate", branch = "update-prometheus" }
sc-client-api = { git = "https://github.com/mxinden/substrate", branch = "update-prometheus" }
sc-consensus = { git = "https://github.com/mxinden/substrate", branch = "update-prometheus" }
sc-light = { git = "https://github.com/mxinden/substrate", branch = "update-prometheus" }
sc-service = { git = "https://github.com/mxinden/substrate", branch = "update-prometheus", features = ["test-helpers"],  default-features = false }
sp-api = { git = "https://github.com/mxinden/substrate", branch = "update-prometheus" }
sp-blockchain = { git = "https://github.com/mxinden/substrate", branch = "update-prometheus" }
sp-core = { git = "https://github.com/mxinden/substrate", branch = "update-prometheus" }
sp-runtime = { git = "https://github.com/mxinden/substrate", branch = "update-prometheus" }
substrate-test-client = { git = "https://github.com/mxinden/substrate", branch = "update-prometheus" }
