[package]
name = "polkadot-statement-table"
version = "0.8.22"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "mxinden-libp2p-0.24.0" }
primitives = { package = "polkadot-primitives", path = "../primitives" }
